id: P006831
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W24823
  title: ལང་ཚོའི་ཞབས་རྗེས
  author: ''
  volumes:
    d30f146bb80e46ed9a3c2555ae0ffb5c:
      image_group_id: I4826
      title: ''
      volume_number: 1
      total_pages: 276
      base_file: v001.txt
